### ISSUE TITLE
[Campaigns / Create] when adding secondary objects, you need to add the ability to add all objects in which the primary object is the parent (except for objects of the list type) in one move. This can significantly save time configuring new campaigns

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2150]
**Front task** https://github.com/Waiviogit/waivio/issues/2149

yammer 1187
Campaigns / Create

when adding secondary objects, you need to add the ability to add all objects in which the primary object is the parent (except for objects of the list type) in one move. This can significantly save time configuring new campaigns
![2021-03-09_09-57](https://user-images.githubusercontent.com/67378322/110437291-e0957e80-80bd-11eb-9891-7a4cfc48b4a7.png)

**Comment by Fesmofet** [comment]
modified request:
https://waiviodev.com/api/docs/#/wobject/get_api_wobject__authorPermlink__child_wobjects
new query property excludeTypes - if you need several types to exclude - duplicate with different values(now only 'list')
in order to get all child elements, the limit property must be equal to 0
![git-2150](https://user-images.githubusercontent.com/59839789/111978974-3251f600-8b0d-11eb-9854-dc704071627e.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
