### ISSUE TITLE
Fix notification text about power up

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2623]
**Front-task** https://github.com/Waiviogit/waivio/issues/2624
**Steps to reproduce**:

1. Log in as hive-user
2. Open wallet
3. Click on Power up button
4. Do operation

**Expected result**: {userName} initiated 'Power Up' on {number} HIVE
**Actual result**: {userName} sent to {userName} {number} HIVE

![2021-05-22_12-39](https://user-images.githubusercontent.com/67378322/119221997-d3076680-bafa-11eb-9847-c2ab08b9c408.png)
![2021-05-22_12-46](https://user-images.githubusercontent.com/67378322/119222196-c3d4e880-bafb-11eb-953a-7ec4ca22a26d.png)

**Comment by YaroslavSemeniuk** [comment]
I created a new notification type 'power_up' which needs to be handled like this: "{userName} initiated 'Power Up' on {amount}" instead of the current "{userName.from} send to {userName.to} {amount}"
![image](https://user-images.githubusercontent.com/73386293/119366728-ee6ca000-bcb9-11eb-9800-53b64391fbf6.png)

**Comment by Diana-Cherry-8** [comment]
**Production checked**
