### ISSUE TITLE
Increase the number of filters by taking tags not from the search on the left panel, but from a map request (where there are 50 objects)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3021]
**Severity**: Minor

**Steps to reproduce**:
1. Open map on site
2. Open search panel

**Expected result**: Tags are displayed in the categories that are displayed on the map, that is, you can select a category and the result will be displayed on the map and in the search bar
**Actual result**: Tags are extended depending on the search results, the search results are taken that are currently displayed on the map and from them tags from the categories are seen. Thus, at least one category on the dishes tab is blocked at the 1st entry, because there are no results for it on the map at the moment

![2021-09-02_13-42](https://user-images.githubusercontent.com/67378322/131830116-bcf73e6d-f6fc-4888-945e-aaca3b7c87c3.png)

**Comment by YaroslavSemeniuk** [comment]
The front should write permlinks from wobjectSerch (where returned 50 wobjects) in wobjectLinks field, when send _tags-for-filter_  request. This will increase the number of tags for wobjects found through the search string. Search depending on the selected area is problematic to implement since the time of execution query will be very long.
![photo_2021-09-22_16-07-36](https://user-images.githubusercontent.com/73386293/134349294-01ecec81-63f3-423a-bf46-e6fc6c4687e2.jpg)
![2021-09-22_16-11](https://user-images.githubusercontent.com/73386293/134349852-d27e3ba5-f4ab-4f24-8dd8-1d8de838118c.png)

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
