### ISSUE TITLE
[recipe / categories] for recipes, it is suggested to add a Categories field, which works the same way as Departments on Products. This is a way to organize recipes into categories on user profiles.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6907]
**Front-task** #6908 

yammer 3887
recipe / categories

for recipes, it is suggested to add a Categories field, which works the same way as Departments on Products. This is a way to organize recipes into categories on user profiles.

![image](https://waivio.nyc3.digitaloceanspaces.com/c63eac94e4679507f8d305f9fa0ed4ed40bd777fe89f95fedc8480154e6c7687)

**Comment by Waiviogit** [comment]
https://waiviodev.com/api/docs/#/shop/post_api_shop_user_departments
https://waiviodev.com/api/docs/#/shop/post_api_shop_user_department_feed
https://waiviodev.com/api/docs/#/shop/post_api_shop_user_main_feed
https://waiviodev.com/api/docs/#/shop/post_api_shop_user_filters
https://waiviodev.com/api/docs/#/shop/post_api_shop_user_filters_tags

in order to display a recipe with categories, you need to add in the user's store request

`"schema" : "recipe"`

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
